/*
* generated by Xtext
*/
package devcpu.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import devcpu.services.DASMGrammarAccess;

public class DASMParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DASMGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected devcpu.parser.antlr.internal.InternalDASMParser createParser(XtextTokenStream stream) {
		return new devcpu.parser.antlr.internal.InternalDASMParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DASMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DASMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
