/*
 * generated by Xtext
 */
package devcpu;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DASMRuntimeModule extends devcpu.AbstractDASMRuntimeModule {

}
