/*
* generated by Xtext
*/
package devcpu;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DASMStandaloneSetup extends DASMStandaloneSetupGenerated{

	public static void doSetup() {
		new DASMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

