/*
 * generated by Xtext
 */
package devcpu.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import devcpu.ui.internal.DASMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DASMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DASMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DASMActivator.getInstance().getInjector(DASMActivator.DEVCPU_DASM);
	}
	
}
