/*
 * generated by Xtext
 */
package devcpu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.model.IResourceForEditorInputFactory;
import org.eclipse.xtext.ui.editor.model.ResourceForIEditorInputFactory;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.SimpleResourceSetProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DASMUiModule extends devcpu.ui.AbstractDASMUiModule {
	public DASMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IResourceForEditorInputFactory>
	    bindIResourceForEditorInputFactory() {
	        return ResourceForIEditorInputFactory.class;
	}
	
	@Override
	public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
	    return SimpleResourceSetProvider.class;
	}
	
	@Override
	public com.google.inject.Provider
	    <org.eclipse.xtext.resource.containers.IAllContainersState>
	    provideIAllContainersState() {
	    return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}
}
